#!/usr/bin/env bash
# print info about domain and subdomain

digIntoServer() {
	domain=$1
	sub=$2
	dig "$sub.$domain" | grep -A1 "ANSWER SECTION" | tail -1 | awk '{ print "The subdomain '"$sub"' is a "$4" record and points to "$5"" }'
}
subdomain=("www" "lb-01" "web-01" "web-02")
if [ $# -eq 1 ]
then
	for sub in "${subdomain[@]}"
	do
		domain=$1
		digIntoServer "$domain" "$sub"
	done
elif [ $# -eq 2 ]
then
	domain=$1
	sub=$2
	digIntoServer "$domain" "$sub"
fi
