#!/usr/bin/env bash
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE=$1
SERVER=$2
USER=$3
KEY=$4

# Transfer the file to the user's home directory on the server using scp
# with no strict host key checking
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$SERVER:~/"
