#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx listening on port 80

apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80 and serve "Hello World!" at root
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
                echo 'Hello World!' > /var/www/html/index.html;
        }
}" > /etc/nginx/sites-available/default

# Restart Nginx with kill
kill -QUIT $(cat /var/run/nginx.pid)
nginx -g "daemon on;"
