#!/usr/bin/env bash
# This script uses IFS to print specified formats
# from the etc passwd file
while IFS=: read -r username gid home shell uid password uid
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $uid"
done < /etc/passwd

