#!/usr/bin/env bash
# This script uses IFS to print specified formats
# from the etc passwd file
while IFS=: read -r user gid dir shell uid pass info
do
	echo "The user $user is part of the $gid gang, lives in $dir and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < /etc/passwd

